/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg252.lab.pkg04;

/**
 *
 * @author nooralsharif
 */
public class DairyFactory extends javax.swing.JFrame {

    /**
     * Creates new form DairyFactory
     */
    public DairyFactory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        carton = new javax.swing.JLabel();
        cheese2 = new javax.swing.JLabel();
        cheese1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        cow = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cheese = new javax.swing.JLabel();
        milk1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(680, 490));
        setMinimumSize(new java.awt.Dimension(680, 490));
        setPreferredSize(new java.awt.Dimension(680, 490));
        setSize(new java.awt.Dimension(680, 490));
        getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/reo.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 90, 100, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/reo.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 20, 100, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/or.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 270, 100, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/or.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 280, 100, 90);

        carton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/carton copy.png"))); // NOI18N
        getContentPane().add(carton);
        carton.setBounds(510, 170, 190, 120);

        cheese2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/cheese copy.png"))); // NOI18N
        getContentPane().add(cheese2);
        cheese2.setBounds(520, 60, 110, 100);

        cheese1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/cheese copy.png"))); // NOI18N
        getContentPane().add(cheese1);
        cheese1.setBounds(520, 0, 110, 100);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Krungthep", 2, 36)); // NOI18N
        jLabel1.setText("CHOOSE A PRODUCT:");

        jButton1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Krungthep", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dairy", "Juice" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(120, 70, 440, 250);

        cow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/cow.png"))); // NOI18N
        getContentPane().add(cow);
        cow.setBounds(500, 260, 180, 240);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/reo.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 50, 100, 60);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/or.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 100, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/oj.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 210, 290);

        cheese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/cheese copy.png"))); // NOI18N
        getContentPane().add(cheese);
        cheese.setBounds(440, 0, 110, 100);

        milk1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/milk1 copy.png"))); // NOI18N
        getContentPane().add(milk1);
        milk1.setBounds(270, 240, 330, 240);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg252/lab/pkg04/ob copy.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 680, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DairyFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DairyFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DairyFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DairyFactory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DairyFactory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel carton;
    private javax.swing.JLabel cheese;
    private javax.swing.JLabel cheese1;
    private javax.swing.JLabel cheese2;
    private javax.swing.JLabel cow;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel milk1;
    // End of variables declaration//GEN-END:variables
}
